# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      - run: mvn package
      
      # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard. 
      - store_test_results: 
          path: petclinic/target/surefire-reports
      - persist_to_workspace:
          root: .
          paths:
            - petclinic/target/petclinic.war
            - Dockerfile

  build-docker:
    machine:
      docker_layer_caching: true 
    steps:
      - attach_workspace:
          at: .
      - run: ls
      - run: docker build -t petclinic:HASH .
  integration-test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      - image: petclinic:HASH
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}        
      - run: mvn integration-test -Pselenium-tests
      - store_test_results: 
          path: petclinic_it/target/surefire-reports
  last-test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo it
  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo deploy

workflows:
  version: 2
  make_ci_great_again:
    jobs:
      - build
      - build-docker:
          requires:
            - build
      - integration-test:
          requires:
            - build-docker
      - last-test:
          requires:
            - build-docker
      - deploy:
          requires:
            - integration-test
            - last-test