version: 2
jobs:
  build:
    docker:
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m  
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results: 
          path: petclinic/target/surefire-reports
      - persist_to_workspace:
          root: .
          paths:
            - petclinic/target/petclinic.war
            - Dockerfile

  build-dockerimage:
    machine:
      docker_layer_caching: true 
    steps:
      - attach_workspace:
          at: .
      - run: docker build -t petclinic:HASH .

  integration-test:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: petclinic:HASH
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}        
      - run: mvn integration-test -Pselenium-tests
      - store_test_results: 
          path: petclinic_it/target/surefire-reports

  last-test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo it

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo deploy